# Pandas

##### Series

In [1]:
import pandas as pd

In [2]:
x=[10,20,30,40]
y=pd.Series(x)
print(y)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
x=["RCB","CSK","DC"]
y=pd.Series(x)
print(y)

0    RCB
1    CSK
2     DC
dtype: object

In [4]:
x={
    "a":1,
    "b":2,
    "c":3
}
y=pd.Series(x)
print(y)

a    1
b    2
c    3
dtype: int64

In [5]:
import numpy as np

In [7]:
ar=np.array([1,2,3,4,5])
y=pd.Series(ar)
print(y)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [8]:
a=range(5)
b=pd.Series(a)
print(b)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [13]:
import random

In [14]:
x=np.random.randint(10)

In [16]:
name=["Virat","Sanju","Dhoni","Rohit"]
run=[83,89,23,67]
data=pd.Series(name,index=run,name="Score")
print(data)

83    Virat
89    Sanju
23    Dhoni
67    Rohit
Name: Score, dtype: object

In [20]:
pwd

'C:\\Users\\LJENG'

In [21]:
f=pd.read_csv("batsman_runs_ipl.csv")
df=pd.DataFrame(f)
df

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [25]:
df.columns

Index(['batter', 'batsman_run'], dtype='object')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   batter       605 non-null    object
 1   batsman_run  605 non-null    int64
dtypes: int64(1), object(1)
memory usage: 9.6+ KB

In [28]:
df.shape

(605, 2)

In [31]:
df.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [32]:
df.tail()

            batter  batsman_run
600     Yash Dayal            0
601  Yashpal Singh           47
602    Younis Khan            3
603   Yuvraj Singh         2754
604         Z Khan          117

In [35]:
l=[[1,2,3],[4,5,6],[7,8,9]]
d=pd.DataFrame(l)
d

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [40]:
df.set_index(df["batsman_run"],inplace=True)

In [41]:
df

                     batter  batsman_run
batsman_run
280          A Ashish Reddy          280
161                A Badoni          161
4                A Chandila            4
53                 A Chopra           53
25              A Choudhary           25
...                     ...          ...
0                Yash Dayal            0
47            Yashpal Singh           47
3               Younis Khan            3
2754           Yuvraj Singh         2754
117                  Z Khan          117

[605 rows x 2 columns]

In [1]:
import pandas as pd

In [2]:
f=pd.read_csv("ipl-matches.csv")

In [3]:
df=pd.DataFrame(f)

In [4]:
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [7]:
df[df["SuperOver"]=="Y"].shape[0]

14

In [9]:
df[(df["WinningTeam"]=="Chennai Super Kings") & (df["City"]=="Kolkata")].shape[0]

5

In [10]:
df[(df["WinningTeam"]=="Gujarat Titans") & (df["TossWinner"]=="Gujarat Titans") & (df["TossDecision"]=="bat")].shape[0]

2

In [12]:
df["Player_of_Match"].unique()

array(['HH Pandya', 'JC Buttler', 'RM Patidar', 'DA Miller',
       'Harpreet Brar', 'JJ Bumrah', 'R Ashwin', 'V Kohli', 'Q de Kock',
       'RA Tripathi', 'SN Thakur', 'TA Boult', 'WP Saha', 'AD Russell',
       'JM Bairstow', 'DR Sams', 'MR Marsh', 'Shubman Gill', 'DP Conway',
       'PWH de Silva', 'Avesh Khan', 'YBK Jaiswal', 'TH David',
       'DA Warner', 'HV Patel', 'K Rabada', 'RK Singh', 'RD Gaikwad',
       'Mohsin Khan', 'SA Yadav', 'R Tewatia', 'KH Pandya',
       'Kuldeep Yadav', 'Umran Malik', 'R Parag', 'S Dhawan', 'KL Rahul',
       'M Jansen', 'Rashid Khan', 'Mukesh Choudhary', 'F du Plessis',
       'YS Chahal', 'KD Karthik', 'MA Agarwal', 'S Dube', 'KS Williamson',
       'Anuj Rawat', 'Abhishek Sharma', 'PJ Cummins', 'LS Livingstone',
       'LH Ferguson', 'UT Yadav', 'E Lewis', 'SV Samson',
       'Mohammed Shami', 'OF Smith', 'VR Iyer', 'SP Narine', 'KS Bharat',
       'Ishan Kishan', 'Shivam Mavi', 'NM Coulter-Nile', 'AR Patel',
       'GJ Maxwell', 'JR Hazlewood', 'KA Pollard', 'JJ Roy', 'RA Jadeja',
       'SS Iyer', 'JO Holder', 'DJ Bravo', 'A Nortje', 'Kartik Tyagi',
       'CV Varun', 'PP Shaw', 'AB de Villiers', 'EJG Morgan', 'CH Morris',
       'D Padikkal', 'A Mishra', 'MM Ali', 'DL Chahar', 'JD Unadkat',
       'RD Chahar', 'N Rana', 'MP Stoinis', 'S Nadeem', 'Sandeep Sharma',
       'BA Stokes', 'CH Gayle', 'CJ Jordan', 'MK Pandey',
       'Mohammed Siraj', 'SR Watson', 'PK Garg', 'RG Sharma', 'AT Rayudu',
       'RR Pant', 'SO Hetmyer', 'MS Dhoni', nan, 'VR Aaron', 'KK Ahmed',
       'PA Patel', 'SPD Smith', 'SL Malinga', 'Imran Tahir', 'KMA Paul',
       'HF Gurney', 'AS Joseph', 'Harbhajan Singh', 'S Gopal',
       'SM Curran', 'L Ngidi', 'CA Lynn', 'Mujeeb Ur Rahman',
       'TG Southee', 'AS Rajpoot', 'JC Archer', 'B Stanlake',
       'SW Billings', 'KV Sharma', 'Washington Sundar', 'KK Nair',
       'MM Sharma', 'DR Smith', 'LMP Simmons', 'G Gambhir', 'AJ Tye',
       'RV Uthappa', 'HM Amla', 'MJ McClenaghan', 'SK Raina', 'B Kumar',
       'CJ Anderson', 'KM Jadhav', 'Yuvraj Singh', 'BCJ Cutting',
       'MC Henriques', 'YK Pathan', 'AB Dinda', 'A Zampa', 'P Kumar',
       'A Nehra', 'AM Rahane', 'CR Brathwaite', 'Mustafizur Rahman',
       'M Vohra', 'AJ Finch', 'P Negi', 'Z Khan', 'PP Chawla',
       'Mandeep Singh', 'BB McCullum', 'MA Starc', 'SE Marsh',
       'JP Duminy', 'GJ Bailey', 'DJ Hooda', 'JP Faulkner', 'M Morkel',
       'V Sehwag', 'MEK Hussey', 'DW Steyn', 'PV Tambe', 'M Vijay',
       'JH Kallis', 'BJ Hodge', 'LJ Wright', 'Azhar Mahmood', 'AP Tare',
       'AC Gilchrist', 'MG Johnson', 'KK Cooper', 'SR Tendulkar',
       'DJG Sammy', 'I Sharma', 'Harmeet Singh', 'R Vinay Kumar',
       'GH Vihari', 'MS Gony', 'SK Trivedi', 'R Dravid', 'MS Bisla',
       'Shakib Al Hasan', 'DJ Hussey', 'A Chandila', 'BW Hilfenhaus',
       'KC Sangakkara', 'CL White', 'B Lee', 'SC Ganguly',
       'KMDN Kulasekara', 'KP Pietersen', 'JD Ryder', 'AD Mascarenhas',
       'L Balaji', 'MN Samuels', 'IK Pathan', 'RE Levi', 'MM Patel',
       'JEC Franklin', 'S Aravind', 'BA Bhatt', 'R Sharma',
       'Iqbal Abdulla', 'P Parameswaran', 'LRPL Taylor', 'JA Morkel',
       'J Botha', 'MK Tiwary', 'DE Bollinger', 'SK Warne',
       'DPMD Jayawardene', 'S Sohal', 'PC Valthaty', 'MD Mishra',
       'SB Wagh', 'S Anirudha', 'A Kumble', 'M Kartik', 'A Symonds',
       'R McLaren', 'RJ Harris', 'TL Suman', 'MJ Lumb', 'PD Collingwood',
       'NV Ojha', 'AC Voges', 'J Theron', 'AA Jhunjhunwala', 'ML Hayden',
       'WPUJC Vaas', 'AD Mathews', 'M Muralitharan', 'LR Shukla',
       'R Bhatia', 'S Badrinath', 'A Singh', 'GC Smith', 'SB Jakati',
       'DP Nannes', 'MV Boucher', 'HH Gibbs', 'TM Dilshan', 'PP Ojha',
       'RS Bopara', 'RP Singh', 'DL Vettori', 'M Ntini', 'CRD Fernando',
       'Sohail Tanvir', 'Umar Gul', 'SP Goswami', 'SM Pollock',
       'ST Jayasuriya', 'Shoaib Akhtar', 'S Sreesanth', 'SA Asnodkar',
       'GD McGrath', 'SM Katich', 'JDP Oram', 'MF Maharoof'], dtype=object)

In [14]:
df[(df["Player_of_Match"]=="MS Dhoni") & ((df["Team1"]=="Mumbai Indians") | (df["Team2"]=="Mumbai Indians"))].shape[0]

1

In [13]:
df["Player_of_Match"]

0          HH Pandya
1         JC Buttler
2         RM Patidar
3          DA Miller
4      Harpreet Brar
           ...
945        DJ Hussey
946       MV Boucher
947      MF Maharoof
948       MEK Hussey
949      BB McCullum
Name: Player_of_Match, Length: 950, dtype: object

In [16]:
df[df["WinningTeam"]=="Gujarat Titans"].shape[0]

12

In [17]:
 import pandas as pd
data = {
    "EmpID":[101,102,103,104,105],
    "Dept":["IT","HR","IT","Finance","HR"],
    "Salary":[60000,45000,80000,75000,50000],
    "Age":[25,32,29,41,28]
}

In [20]:
df=pd.DataFrame(data)

In [21]:
df.sort_values(by="Dept")

   EmpID     Dept  Salary  Age
3    104  Finance   75000   41
1    102       HR   45000   32
4    105       HR   50000   28
0    101       IT   60000   25
2    103       IT   80000   29

In [23]:
df.sort_values(by="Salary",ascending=False,inplace=True)

In [24]:
df

   EmpID     Dept  Salary  Age
2    103       IT   80000   29
3    104  Finance   75000   41
0    101       IT   60000   25
4    105       HR   50000   28
1    102       HR   45000   32

In [25]:
df.sort_index(ascending=False)

   EmpID     Dept  Salary  Age
4    105       HR   50000   28
3    104  Finance   75000   41
2    103       IT   80000   29
1    102       HR   45000   32
0    101       IT   60000   25

In [26]:
import pandas as pd
df = pd.DataFrame({
    "Student":["A","B","C","D"],
    "Math":[70,45,90,60],
    "Science":[75,40,85,55]
})

In [27]:
df

  Student  Math  Science
0       A    70       75
1       B    45       40
2       C    90       85
3       D    60       55

In [28]:
df["Grade"]=0

In [29]:
df

  Student  Math  Science  Grade
0       A    70       75      0
1       B    45       40      0
2       C    90       85      0
3       D    60       55      0

In [30]:
df.groupby("Student")[["Math","Science"]].sum()

         Math  Science
Student
A          70       75
B          45       40
C          90       85
D          60       55

In [31]:
df[["Math","Science"]].sum()

Math       265
Science    255
dtype: int64

In [42]:
import pandas as pd
df1 = pd.DataFrame({
    "ID":[1,2,3],
    "Name":["A","B","C"]
})
df2 = pd.DataFrame({
    "ID":[2,3,4],
    "Marks":[80,90,70]
})

In [43]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [44]:
df2

   ID  Marks
0   2     80
1   3     90
2   4     70

In [46]:
df3=pd.concat([df1,df2],join="outer")

In [40]:
pd.concat([df1,df2],join="inner")

   ID
0   1
1   2
2   3
0   2
1   3
2   4

In [45]:
pd.concat([df1,df2])

   ID Name  Marks
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   2  NaN   80.0
1   3  NaN   90.0
2   4  NaN   70.0

In [49]:
df3.isnull().sum()

ID       0
Name     3
Marks    3
dtype: int64

In [2]:
f=pd.read_csv("ipl-matches.csv")

In [6]:
df=pd.DataFrame(f)
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [9]:
df[(df["WinningTeam"]=="Gujarat Titans") & (df["SuperOver"]=="Y")].shape[0]

0

In [24]:
df[(df["WinningTeam"]=="Royal Challengers Bangalore")&((df["Team1"]=="Kolkata Knight Riders")|(df["Team2"]=="Kolkata Knight Riders"))].shape[0]

14

In [12]:
df[df["TossWinner"]==df["WinningTeam"]].shape[0]

489

In [14]:
df["method"].unique()

array([nan, 'D/L'], dtype=object)

In [21]:
df[(df["method"]=="D/L") & (df["WonBy"]=="Wickets")].shape[0]

8

In [22]:
df[(df["TossWinner"]=="Rajasthan Royals")&(df["WinningTeam"]=="Rajasthan Royals")].shape[0]

49

In [25]:
df[(df["Player_of_Match"]=="V Kohli")&((df["Team1"]=="Chennai Super Kings")|(df["Team2"]=="Chennai Super Kings"))].shape[0]

2

In [27]:
df[(df["City"]=="Dubai")&(df["MatchNumber"]=="Final")]["TossWinner"]

74    Kolkata Knight Riders
Name: TossWinner, dtype: object

In [28]:
df[(df["MatchNumber"]=="Final")& ((df["Team1"]=="Kolkata Knight Riders")|(df["Team2"]=="Kolkata Knight Riders"))&
   (df["TossWinner"]=="Kolkata Knight Riders")&(df["TossDecision"]=="field")].shape[0]

2

In [29]:
df.corr??