In [3]:
from bs4 import BeautifulSoup

In [4]:
with open("beautifulsoup_practice.html","r") as f:
    html=f.read()
    print(html)

<!DOCTYPE html>
<html>

<head>
    <title>BeautifulSoup Practice Website</title>
</head>

<body>

    <h1 id="main-title">LJU Student Portal</h1>

    <div class="student" data-id="101">

        <h2 class="name">Dhruv Patel</h2>

        <p class="department">Computer Engineering</p>

        <p class="email">
            Email:
            <span>dhruv@gmail.com</span>
        </p>

        <a href="https://linkedin.com/dhruv">
            LinkedIn Profile
        </a>

        <img src="dhruv.jpg" alt="Dhruv Image">

    </div>

    <div class="student" data-id="102">

        <h2 class="name">Riya Shah</h2>

        <p class="department">IT Engineering</p>

        <p class="email">
            Email:
            <span>riya@gmail.com</span>
        </p>

        <a href="https://linkedin.com/riya">
            LinkedIn Profile
        </a>

        <img src="riya.jpg" alt="Riya Image">

    </div>

    <div class="student" data-id="103">

        <h2 class="name">Amit Joshi</h2>

        <p class="department">AI & DS</p>

        <p class="email">
            Email:
            <span>amit@gmail.com</span>
        </p>

        <a href="https://linkedin.com/amit">
            LinkedIn Profile
        </a>

        <img src="amit.jpg" alt="Amit Image">

    </div>

    <hr>

    <h2>Student Marks Table</h2>

    <table border="1" id="marks-table">

        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Python</th>
            <th>Django</th>
        </tr>

        <tr>
            <td>101</td>
            <td>Dhruv</td>
            <td>95</td>
            <td>90</td>
        </tr>

        <tr>
            <td>102</td>
            <td>Riya</td>
            <td>88</td>
            <td>91</td>
        </tr>

        <tr>
            <td>103</td>
            <td>Amit</td>
            <td>92</td>
            <td>85</td>
        </tr>

    </table>

</body>
</html>

In [5]:
soup=BeautifulSoup(html,"html.parser")
z=soup.find("h2")
z

In [6]:
z.text

'Dhruv Patel'

In [7]:
p=soup.find("p").text.strip()
p

'Computer Engineering'

In [8]:
details=soup.find("div",{"class":"student"}).text.strip()

In [9]:
title=soup.find("h1",{"id":"main-title"}).text.strip()

In [10]:
title

'LJU Student Portal'

In [11]:
name=soup.find("h2",{"class":"name"}).text
name

'Dhruv Patel'

In [12]:
dep=soup.find("p",{"class":"department"}).text
dep

'Computer Engineering'

In [13]:
email=soup.find("span").text.strip()
email

'dhruv@gmail.com'

In [14]:
social=soup.find("a").text.strip()
social

'LinkedIn Profile'

In [15]:
data={"Title":[title],
     "Name":[name],
     "Department":[dep],
     "Email":[email],
     "Social":[social]}

In [16]:
import pandas as pd

In [17]:
df=pd.DataFrame(data)
df

,Title,Name,Department,Email,Social
0,LJU Student Portal,Dhruv Patel,Computer Engineering,dhruv@gmail.com,LinkedIn Profile

In [18]:
l1=soup.find_all("div",class_="student")[0:2]
print(len(l1))

2

In [19]:
name=[]
dep=[]
email=[]
ext=[]
social=[]
link=[]
img=[]
for i in l1:
    n=i.find("h2").text
    name.append(n)
    d=i.find("p").text
    dep.append(d)
    e=i.find("span").text
    ex=e.split('@')
    email.append(ex[0])
    ext.append(ex[1])
    s=i.find("a").text.strip()
    social.append(s)
    l=i.find("a")
    link.append(l["href"])
    im=i.find("img")
    img.append(im["src"])

In [20]:
data={"Title":title,
     "Name":name,
     "Department":dep,
     "Email":email,
      "Ext":ext,
     "Social":social,
     "Link":link,
     "Image":img}

In [21]:
df=pd.DataFrame(data)
df

,Title,Name,Department,Email,Ext,Social,Link,Image
0,LJU Student Portal,Dhruv Patel,Computer Engineering,dhruv,gmail.com,LinkedIn Profile,https://linkedin.com/dhruv,dhruv.jpg
1,LJU Student Portal,Riya Shah,IT Engineering,riya,gmail.com,LinkedIn Profile,https://linkedin.com/riya,riya.jpg

In [22]:
import requests

In [1]:
from bs4 import BeautifulSoup

In [25]:
url="https://www.politifact.com/factchecks/list/"
data=requests.get(url)
data.status_code
html=data.text

In [36]:
soup=BeautifulSoup(html,"html.parser")
z=soup.find_all("li",class_="o-listicle__item")
name=[]
date=[]
info=[]
author=[]
for i in z:
    n=i.find("a",class_="m-statement__name").text.strip()
    name.append(n)
    d=i.find("footer",class_="m-statement__footer").text.strip()
    a=d.split("•")
    date.append(a[1])
    author.append(a[0])
    inf=i.find("div",class_="m-statement__desc").text.strip()
    info.append(inf)

In [37]:
import pandas as pd
data={
    "Name":name,
    "Info":info,
    "Date":date,
    "Author":author
}
df=pd.DataFrame(data)

In [38]:
df

,Name,Info,Date,Author
0,Donald Trump,"stated on May 18, 2026 in remarks at the White...","May 20, 2026",By Louis Jacobson
1,Social Media,"stated on May 19, 2026 in in social media posts:","May 20, 2026",By Jeff Cercone
2,X posts,"stated on May 14, 2026 in X posts:","May 15, 2026",By Loreben Tuquero
3,X posts,"stated on May 6, 2026 in an X post:","May 14, 2026",By Maria Briceño
4,Kathy Castor,"stated on April 29, 2026 in an X post:","May 14, 2026",By Samantha Putterman
5,Vivek Ramaswamy,"stated on April 24, 2026 in an ad:","May 13, 2026",By Amy Sherman
6,TikTok posts,"stated on May 8, 2026 in una publicación en Ti...","May 13, 2026",By Maria Briceño
7,Christine Quinn,"stated on March 5, 2026 in a press release:","May 11, 2026",By Andrew McGurl
8,Nicholas Langworthy,"stated on March 31, 2026 in an X post:","May 11, 2026",By Holden Turek
9,Donald Trump,"stated on May 7, 2026 in remarks to reporters:","May 8, 2026",By Louis Jacobson
10,Byron Donalds,"stated on May 4, 2026 in an interview:","May 8, 2026",By Samantha Putterman
11,Marcy Kaptur,"stated on May 5, 2026 in an X post:","May 8, 2026",By Maria Briceño
12,Liz Krueger,"stated on March 5, 2026 in an op-ed:","May 7, 2026",By Conor Amendola
13,X posts,"stated on May 6, 2026 in a social media post:","May 7, 2026",By Louis Jacobson
14,Donald Trump,"stated on May 4, 2026 in a White House event:","May 6, 2026",By Louis Jacobson
15,Sam Sutton,"stated on March 11, 2026 in a rally:","May 5, 2026",By Emma Gavazzi
16,Fentrice Driskell,"stated on April 29, 2026 in an interview:","May 1, 2026",By Samantha Putterman
17,Instagram posts,"stated on April 26, 2026 in una publicación en...","April 30, 2026",By Maria Briceño
18,Bernie Sanders,"stated on April 22, 2026 in a Senate committee...","April 30, 2026",By Amy Sherman
19,Tim Scott,"stated on April 26, 2026 in an X post:","April 29, 2026",By Louis Jacobson
20,Pine Tree Results PAC,"stated on April 26, 2026 in an ad:","April 29, 2026",By Amy Sherman
21,Social Media,"stated on April 26, 2026 in social media posts:","April 29, 2026",By Maria Briceño
22,Donald Trump,"stated on April 23, 2026 in remarks at the Whi...","April 29, 2026",By Louis Jacobson
23,Ron DeSantis,"stated on April 27, 2026 in an interview with ...","April 29, 2026",By Louis Jacobson
24,Social Media,"stated on April 26, 2026 in publicaciones en r...","April 28, 2026",By Maria Briceño
25,Jay Collins,"stated on April 20, 2026 in a campaign document:","April 23, 2026",By Samantha Putterman
26,Robert F. Kennedy Jr.,"stated on April 22, 2026 in testimony to the S...","April 23, 2026",By Louis Jacobson
27,Joe Rogan,"stated on April 18, 2026 in comments at the Ov...","April 22, 2026",By Grace Abels
28,X posts,"stated on April 21, 2026 in an X post:","April 22, 2026",By Maria Briceño
29,Chris Wright,"stated on April 19, 2026 in an interview on CN...","April 22, 2026",By Louis Jacobson

In [37]:
with open("flipkart.html","r",encoding="UTF-8") as f:
    html=f.read()

In [38]:
soup=BeautifulSoup(html,"html.parser")
data=soup.find_all("div",class_="_3pLy-c row")
name=[]
rating=[]
Ram=[]
battery=[]
og=[]
dis=[]
for i in data:
    n=i.find("div",class_="_4rR01T").text.strip()
    name.append(n)
    r=i.find("div",class_="_3LWZlK").text.strip()
    rating.append(r)
    ra=i.find("li",class_="rgWa7D").text.strip()
    Ram.append(ra)
    ba=i.find_all("li",class_="rgWa7D")[3]
    battery.append(ba.text)
    o=i.find("div",class_="_3I9_wc _27UcVY")
    if o:
        og.append(o.text)
    else:
        og.append(0)
    d=i.find("div",class_="_30jeq3 _1_WHN1")
    if d:
        dis.append(d.text)
    else:
        dis.append(0)

In [39]:
import pandas as pd
d={
    "Name":name,
    "Rating":rating,
    "RAM":Ram,
    "Battery":battery,
    "Original price":og,
    "Discount price":dis,
}
df=pd.DataFrame(d)
df

,Name,Rating,RAM,Battery,Original price,Discount price
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹40,999","₹39,999"
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹40,999","₹39,999"
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹1,01,999","₹49,999"
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹95,999","₹44,999"
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹74,999","₹49,999"
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹74,999","₹49,999"
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,"₹45,999","₹40,999"
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,999","₹46,999"
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹1,01,999","₹49,999"
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,999","₹47,349"
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,"₹47,999","₹38,849"
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹95,999","₹44,999"
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹57,990","₹49,999"
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹57,990","₹47,999"
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹48,999"
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹46,999"
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹49,999"
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,A13 Bionic Chip Processor,"₹48,900","₹46,999"
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,0,"₹49,999"
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹79,990","₹43,990"
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹79,990","₹43,900"
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,"₹57,999","₹49,999"
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,"₹54,990","₹48,999"
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹84,999","₹48,880"

In [40]:
df["Dis"]=df["Original price"]-(int)df["Discount price"]
df["Original price"]=

SyntaxError: invalid syntax (1520731184.py, line 1)

In [41]:
o=[]
d=[]
for i in df["Original price"]:
    if i:
        o.append(i[1:].replace(",",""))
    else:
        o.append(0)
for i in df["Discount price"]:
    d.append(i[1:].replace(",",""))

In [42]:
o

['40999',
 '40999',
 '101999',
 '95999',
 '74999',
 '74999',
 '45999',
 '47999',
 '101999',
 '47999',
 '47999',
 '95999',
 '57990',
 '57990',
 0,
 0,
 0,
 '48900',
 0,
 '79990',
 '79990',
 '57999',
 '54990',
 '84999']

In [43]:
df["OG"]=o

In [44]:
df

,Name,Rating,RAM,Battery,Original price,Discount price,OG
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹40,999","₹39,999",40999
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹40,999","₹39,999",40999
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹1,01,999","₹49,999",101999
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹95,999","₹44,999",95999
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹74,999","₹49,999",74999
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹74,999","₹49,999",74999
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,"₹45,999","₹40,999",45999
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,999","₹46,999",47999
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹1,01,999","₹49,999",101999
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,999","₹47,349",47999
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,"₹47,999","₹38,849",47999
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹95,999","₹44,999",95999
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹57,990","₹49,999",57990
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹57,990","₹47,999",57990
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹48,999",0
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹46,999",0
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹49,999",0
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,A13 Bionic Chip Processor,"₹48,900","₹46,999",48900
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,0,"₹49,999",0
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹79,990","₹43,990",79990
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹79,990","₹43,900",79990
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,"₹57,999","₹49,999",57999
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,"₹54,990","₹48,999",54990
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹84,999","₹48,880",84999

In [45]:
df["OG"].astype(int)

0      40999
1      40999
2     101999
3      95999
4      74999
5      74999
6      45999
7      47999
8     101999
9      47999
10     47999
11     95999
12     57990
13     57990
14         0
15         0
16         0
17     48900
18         0
19     79990
20     79990
21     57999
22     54990
23     84999
Name: OG, dtype: int32

In [46]:
df

,Name,Rating,RAM,Battery,Original price,Discount price,OG
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹40,999","₹39,999",40999
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹40,999","₹39,999",40999
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹1,01,999","₹49,999",101999
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹95,999","₹44,999",95999
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹74,999","₹49,999",74999
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹74,999","₹49,999",74999
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,"₹45,999","₹40,999",45999
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,999","₹46,999",47999
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹1,01,999","₹49,999",101999
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,999","₹47,349",47999
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,"₹47,999","₹38,849",47999
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹95,999","₹44,999",95999
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹57,990","₹49,999",57990
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹57,990","₹47,999",57990
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹48,999",0
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹46,999",0
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,0,"₹49,999",0
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,A13 Bionic Chip Processor,"₹48,900","₹46,999",48900
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,0,"₹49,999",0
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹79,990","₹43,990",79990
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹79,990","₹43,900",79990
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,"₹57,999","₹49,999",57999
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,"₹54,990","₹48,999",54990
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹84,999","₹48,880",84999

In [47]:
df["d"]=d

In [48]:
df["d"].astype(int)

0     39999
1     39999
2     49999
3     44999
4     49999
5     49999
6     40999
7     46999
8     49999
9     47349
10    38849
11    44999
12    49999
13    47999
14    48999
15    46999
16    49999
17    46999
18    49999
19    43990
20    43900
21    49999
22    48999
23    48880
Name: d, dtype: int32

In [49]:
df["Dis"]=df["OG"]-df["d"]

TypeError: unsupported operand type(s) for -: 'str' and 'str'